###########################
##### RUN BUILD #####
###########################
FROM gradle:7.2.0-jdk11

RUN mkdir -p  /home/gradle/src/temp
COPY --chown=gradle:gradle . /home/gradle/src/temp

ARG SUB_MODULE

WORKDIR /home/gradle/src/temp

RUN gradle --no-daemon --debug :clean
RUN gradle --no-daemon --debug -x test :dependencies

WORKDIR /
RUN rm -r /home/gradle/src/temp

