spring.application.name: file-storage

spring:
  profiles:
    group:
      "dev": "dev-app"
      "prod": "prod-app"

---
spring.config.activate.on-profile: dev
spring.cloud.config.enabled: false
---
spring.config.activate.on-profile: test
spring.cloud.config.enabled: false
---
spring.config.activate.on-profile: prod
spring.cloud.config.enabled: false
